package edu.icet.crm.dao.util;

public enum DaoType {
    PLACE_ORDER_DAO,ORDERS_VIEW_DAO,ITEMS_VIEW_DAO,CUSTOMER_REPORTS_VIEW_DAO, ORDER_REPORTS_VIEW_DAO,
    USERS_VIEW_DAO,LOGIN_VIEW_DAO,PART_DAO
}
